
title: Fusion Development Hands-On Lab
description: Companion lab for designing Power Apps for custom solutions using Fusion-based approaches. 

# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

baseurl: "/taw-power-apps-power-platform" 
url: "https://felihong.github.io"