title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!

# theme: just-the-docs
remote-theme: just-the-docs

baseurl: "" 
url: "https://felihong.github.io/taw-power-apps-power-platform/docs"