source 'https://rubygems.org'
# installed by `gem jekyll`
gem "jekyll", "~> 4.3" 
# required when using Ruby >= 3 and Jekyll <= 4.2.2
gem "webrick" 
# always download the latest release
gem "just-the-docs" 